name: pull_request

on:
    pull_request:
      types: [opened, reopened, synchronize]

jobs:
   tests:
        name: tests
        uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
